### ISSUE TITLE
ระดับ การคัดกรอง ROP screening ไม่ครบค่ะ

### ISSUE THREAD

**Issue by supattrakkh** [dixonsatit/newborn#15]
ระดับผลการตรวจ ROP Screening ขาด ผล NO ROP ค่ะ

**Comment by supattrakkh** [comment]
![rop](https://cloud.githubusercontent.com/assets/23182415/19879320/046981d2-a024-11e6-8f36-98620a357713.png)

**Comment by dixonsatit** [comment]
ok เดี่ยวเพิ่มให้ครับ

**Comment by supattrakkh** [comment]
ขอบคุณค่ะ

**Comment by dixonsatit** [comment]
เพิ่ม No Stage แล้วครับ
<img width="1010" alt="screen shot 2016-11-01 at 11 24 50" src="https://cloud.githubusercontent.com/assets/1027274/19879495/e605555c-a025-11e6-97db-0b3c3afbaa73.png">

**Comment by supattrakkh** [comment]
NO ROP ค่ะ

**Comment by dixonsatit** [comment]
NO ROP เรียบร้อย
