### ISSUE TITLE
ไม่มีที่ให้ค้น HN เพื่อหาข้อมูลเด็กที่ลงทะเบียนไปแล้วค่ะ 

### ISSUE THREAD

**Issue by supattrakkh** [dixonsatit/newborn#16]
![1](https://cloud.githubusercontent.com/assets/23182415/19879441/23733bee-a025-11e6-85bf-dab7a00eea51.png)

**Comment by dixonsatit** [comment]
ค้นเจออยู่นะ! 
![Uploading Screen Shot 2016-11-01 at 11.29.39.png…]()

**Comment by dixonsatit** [comment]
<img width="999" alt="screen shot 2016-11-01 at 11 29 39" src="https://cloud.githubusercontent.com/assets/1027274/19879563/a1c697e2-a026-11e6-94c3-433a8b986acb.png">

**Comment by supattrakkh** [comment]
ได้แล้วค่ะ
